version: "3.8"

services:
  pocketbase:
    image: waschraum/pocketbase:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waschraum_pocketbase_backend
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - tunnel-network
    volumes:
      - "./base/pb_data:/pb/pb_data" # Attaches pb_data to a volume named 'pocketbase-data' on your current directory

networks:
  tunnel-network:
    external: true
